"""extend_proto_models

Revision ID: 2823e2ccfea9
Revises: 2656328c42c5
Create Date: 2026-06-05 09:50:35.957141

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2823e2ccfea9"
down_revision: str | None = "2656328c42c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_app_name_per_ws", "applications", ["workspace_id", "application_name"]
    )
    op.add_column(
        "open_ui_specs",
        sa.Column("prompt_text", sa.Text(), nullable=True, comment="提交给 OpenUI 服务的提示词"),
    )
    op.add_column(
        "open_ui_specs", sa.Column("page_count", sa.Integer(), nullable=True, comment="生成页面数")
    )
    op.add_column(
        "open_ui_specs",
        sa.Column("page_titles_json", sa.Text(), nullable=True, comment="页面标题列表 JSON"),
    )
    op.add_column(
        "open_ui_specs", sa.Column("service_status", sa.String(length=16), nullable=False)
    )
    op.add_column("open_ui_specs", sa.Column("generation_duration_ms", sa.Integer(), nullable=True))
    op.add_column("open_ui_specs", sa.Column("content_hash", sa.String(length=64), nullable=True))
    op.drop_column("open_ui_specs", "dsl_json")
    op.add_column(
        "sketches",
        sa.Column(
            "source_story_ids", sa.Text(), nullable=True, comment="参与生成的用户故事 ID 列表 JSON"
        ),
    )
    op.add_column(
        "sketches", sa.Column("page_count", sa.Integer(), nullable=True, comment="生成页面数")
    )
    op.add_column(
        "sketches", sa.Column("coverage_percent", sa.Integer(), nullable=True, comment="字段覆盖率")
    )
    op.drop_column("sketches", "image_url")
    op.drop_column("sketches", "annotations")
    op.create_unique_constraint("uq_skill_name_version", "skills", ["skill_name", "version"])
    op.add_column(
        "wireframes",
        sa.Column(
            "c4_dsl_store_id", sa.String(length=36), nullable=True, comment="关联的 C4 DSL 版本"
        ),
    )
    op.add_column("wireframes", sa.Column("pipeline_stage", sa.String(length=16), nullable=False))
    op.add_column(
        "wireframes", sa.Column("page_count", sa.Integer(), nullable=True, comment="生成页面数")
    )
    op.add_column(
        "wireframes",
        sa.Column("avg_confidence", sa.Integer(), nullable=True, comment="平均映射置信度"),
    )
    op.drop_column("wireframes", "nodes")
    op.drop_column("wireframes", "edges")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wireframes", sa.Column("edges", sa.TEXT(), nullable=False))
    op.add_column("wireframes", sa.Column("nodes", sa.TEXT(), nullable=False))
    op.drop_column("wireframes", "avg_confidence")
    op.drop_column("wireframes", "page_count")
    op.drop_column("wireframes", "pipeline_stage")
    op.drop_column("wireframes", "c4_dsl_store_id")
    op.drop_constraint("uq_skill_name_version", "skills", type_="unique")
    op.add_column("sketches", sa.Column("annotations", sa.TEXT(), nullable=True))
    op.add_column("sketches", sa.Column("image_url", sa.VARCHAR(length=512), nullable=False))
    op.drop_column("sketches", "coverage_percent")
    op.drop_column("sketches", "page_count")
    op.drop_column("sketches", "source_story_ids")
    op.add_column("open_ui_specs", sa.Column("dsl_json", sa.TEXT(), nullable=False))
    op.drop_column("open_ui_specs", "content_hash")
    op.drop_column("open_ui_specs", "generation_duration_ms")
    op.drop_column("open_ui_specs", "service_status")
    op.drop_column("open_ui_specs", "page_titles_json")
    op.drop_column("open_ui_specs", "page_count")
    op.drop_column("open_ui_specs", "prompt_text")
    op.drop_constraint("uq_app_name_per_ws", "applications", type_="unique")
    # ### end Alembic commands ###
