"""add_c4_baseline_fragment_binding

Revision ID: 81d6fdeacf5b
Revises: 99922dccb084
Create Date: 2026-06-10 19:33:09.690560

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '81d6fdeacf5b'
down_revision: str | None = '99922dccb084'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'binding_records',
        sa.Column('binding_id', sa.String(length=36), nullable=False),
        sa.Column('project_id', sa.String(length=36), nullable=False),
        sa.Column('artifact_id', sa.String(length=200), nullable=False),
        sa.Column('artifact_type', sa.String(length=50), nullable=False),
        sa.Column('c4_node_id', sa.String(length=200), nullable=False),
        sa.Column('c4_level', sa.String(length=5), nullable=False),
        sa.Column('relation_type', sa.String(length=20), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('source_location', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint("c4_level IN ('L1','L2','L3','L4')", name='ck_binding_c4_level'),
        sa.CheckConstraint(
            "relation_type IN ('binds_to','injects_into','implements','locates_at','generates')",
            name='ck_binding_relation_type',
        ),
        sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_binding_confidence'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('binding_id'),
    )
    op.create_table(
        'c4_baselines',
        sa.Column('baseline_id', sa.String(length=36), nullable=False),
        sa.Column('project_id', sa.String(length=36), nullable=False),
        sa.Column('version', sa.String(length=20), nullable=False),
        sa.Column('dsl_content', sa.Text(), nullable=False),
        sa.Column('dsl_hash', sa.String(length=64), nullable=False),
        sa.Column('level', sa.String(length=10), nullable=False),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('compiled_from', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint("level IN ('L1','L2','L3','L4','L1-L4')", name='ck_c4_baseline_level'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('baseline_id'),
    )
    op.create_table(
        'fragments',
        sa.Column('fragment_id', sa.String(length=36), nullable=False),
        sa.Column('project_id', sa.String(length=36), nullable=False),
        sa.Column('module_id', sa.String(length=36), nullable=True),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('slug', sa.String(length=200), nullable=False),
        sa.Column('doc_type', sa.String(length=50), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('content_hash', sa.String(length=64), nullable=False),
        sa.Column('state', sa.String(length=16), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('metadata_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "doc_type IN ('PRD','DOMAIN_MODEL','ARCH','DETAIL_DESIGN','API_DESIGN','DB_DESIGN','OTHER')",
            name='ck_fragment_doc_type',
        ),
        sa.CheckConstraint(
            "state IN ('DRAFT','REVIEW','APPROVED','DEPRECATED')",
            name='ck_fragment_state',
        ),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('fragment_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fragments')
    op.drop_table('c4_baselines')
    op.drop_table('binding_records')
    # ### end Alembic commands ###
