"""add_c4_manual_override

Revision ID: 99922dccb084
Revises: 2823e2ccfea9
Create Date: 2026-06-05 09:32:17.888806

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '99922dccb084'
down_revision: str | None = '2823e2ccfea9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'c4_dsl_stores',
        sa.Column('is_manual', sa.Boolean(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c4_dsl_stores', 'is_manual')
    # ### end Alembic commands ###
