"""add_gap_status_to_interface_contracts

Revision ID: c013016fecf7
Revises: 1427fce328a4
Create Date: 2026-06-11 19:25:38.356397

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c013016fecf7"
down_revision: str | None = "1427fce328a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bypass_records", sa.Column("gate_decision_id", sa.String(length=36), nullable=True)
    )
    op.create_index(
        op.f("ix_bypass_records_gate_decision_id"),
        "bypass_records",
        ["gate_decision_id"],
        unique=False,
    )
    op.add_column(
        "open_ui_specs",
        sa.Column("prompt_text", sa.Text(), nullable=True, comment="提交给 OpenUI 服务的提示词"),
    )
    op.add_column(
        "open_ui_specs", sa.Column("page_count", sa.Integer(), nullable=True, comment="生成页面数")
    )
    op.add_column(
        "open_ui_specs",
        sa.Column("page_titles_json", sa.Text(), nullable=True, comment="页面标题列表 JSON"),
    )
    op.add_column(
        "open_ui_specs", sa.Column("service_status", sa.String(length=16), nullable=False)
    )
    op.add_column("open_ui_specs", sa.Column("generation_duration_ms", sa.Integer(), nullable=True))
    op.add_column("open_ui_specs", sa.Column("content_hash", sa.String(length=64), nullable=True))
    op.drop_column("open_ui_specs", "dsl_json")

    with op.batch_alter_table("applications") as batch_op:
        batch_op.create_unique_constraint(
            "uq_app_name_per_ws", ["workspace_id", "application_name"]
        )
    with op.batch_alter_table("skills") as batch_op:
        batch_op.create_unique_constraint("uq_skill_name_version", ["skill_name", "version"])
    with op.batch_alter_table("interface_contracts") as batch_op:
        batch_op.drop_constraint("ck_contract_status", type_="check")
        batch_op.create_check_constraint(
            "ck_contract_status", "status IN ('DRAFT','FROZEN','GAP','DEPRECATED')"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("open_ui_specs", sa.Column("dsl_json", sa.TEXT(), nullable=False))
    op.drop_column("open_ui_specs", "content_hash")
    op.drop_column("open_ui_specs", "generation_duration_ms")
    op.drop_column("open_ui_specs", "service_status")
    op.drop_column("open_ui_specs", "page_titles_json")
    op.drop_column("open_ui_specs", "page_count")
    op.drop_column("open_ui_specs", "prompt_text")
    op.drop_index(op.f("ix_bypass_records_gate_decision_id"), table_name="bypass_records")
    op.drop_column("bypass_records", "gate_decision_id")

    with op.batch_alter_table("skills") as batch_op:
        batch_op.drop_constraint("uq_skill_name_version", type_="unique")
    with op.batch_alter_table("applications") as batch_op:
        batch_op.drop_constraint("uq_app_name_per_ws", type_="unique")
    with op.batch_alter_table("interface_contracts") as batch_op:
        batch_op.drop_constraint("ck_contract_status", type_="check")
        batch_op.create_check_constraint(
            "ck_contract_status", "status IN ('DRAFT','FROZEN','DEPRECATED')"
        )
    # ### end Alembic commands ###
